controller:
  repository: xcentralnn/curator-controller
  tag: "v1.0.1"

mlEngine:
  repository: xcentralnn/curator-ml-engine
  tag: "v1.0.1"

ui:
  enabled: true
  repository: xcentralnn/curator-ui
  tag: "v1.0.1"
