apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "curator.fullname" . }}-controller
  labels:
    {{- include "curator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "curator.fullname" . }}-controller
  labels:
    {{- include "curator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
rules:
  - apiGroups:
      - curator.io
      - xcentralnn.io
    resources:
      - curatorscalers
      - curatorscalers/status
      - curatorscalers/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "curator.fullname" . }}-controller
  labels:
    {{- include "curator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "curator.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "curator.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "curator.fullname" . }}-controller
  labels:
    {{- include "curator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "curator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "curator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "curator.fullname" . }}-controller
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
